
version: 2.1

jobs:
  
  integration-redshift:
    docker:
      - image: circleci/python:3.6.3-stretch
    steps:
      - checkout
      - run:
          name: "Run Tests - Redshift"
          command: ./run_test.sh redshift
      - store_artifacts:
          path: ./logs
      
  integration-snowflake:
    docker:
      - image: circleci/python:3.6.3-stretch
    steps:
      - checkout
      - run:
          name: "Run Tests - Snowflake"
          command: ./run_test.sh snowflake
      - store_artifacts:
          path: ./logs

  integration-databricks:
    environment:
      ODBC_DRIVER: Simba
    docker:
      - image: fishtownanalytics/test-container:9
    steps:
      - checkout
      - run:
          name: "Run Tests - Databricks"
          command: ./run_test.sh databricks
      - store_artifacts:
          path: ./logs


workflows:
  version: 2
  test-all:
    jobs:
      - integration-redshift
      - integration-snowflake
      - integration-databricks
